### ISSUE TITLE
Open pfi_verification_page in native browser

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/didpay#25]
Would it make sense for the PFI verification page, instead of using a webview, opens the native platform browser, and then handle any didpay:// callbacks? 

Benefits: 
* Use familiar browser and encourage users to be aware of what they are browsing to
* Works better with webapp (if this app is to also be a web app): or else a workaround like https://pub.dev/packages/webview_flutter_web is needed

@ethan-tbd wasn't sure if there is some reasoning around using a webview so feel free to ignore.

**Comment by ethan-tbd** [comment]
@michaelneale we considered utilizing deep links and opening up the native browser (safari, chrome, etc) but ultimately decided to go with the webview approach to keep the entire experience within the didpay app. think the focus is on mobile atm in order to unlock a mobile tbDEX interaction but webapp support should definitely be on the roadmap (à la didpay versions 1-3)!

**Comment by michaelneale** [comment]
SGTM
